<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="prometheus-net.AspNetCore" Version="8.2.1" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ShadowLure.Core\ShadowLure.Core.csproj" />
    <ProjectReference Include="..\ShadowLure.Shadow\ShadowLure.Shadow.csproj" />
    <ProjectReference Include="..\ShadowLure.Profiling\ShadowLure.Profiling.csproj" />
    <ProjectReference Include="..\ShadowLure.Infrastructure\ShadowLure.Infrastructure.csproj" />
  </ItemGroup>
</Project>
